const data = {
  products: [
    {
      _id: "1",
      name: "OLIVA V PACK 5",
      category: "Cigars",
      image: "/images/p-1.png",
      price: 695,
      countInStock: 50,
      brand: "Montana",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Montana LE AMI pack 10",
      category: "Cigars",
      image: "/images/p-2.jpeg",
      price: 220,
      countInStock: 50,
      brand: "Montana",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "LA GLORIA CUBANA",
      category: "Cigars",
      image: "/images/p-3.jpeg",
      price: 420,
      countInStock: 50,
      brand: "Montana",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "La Gloria Cubana Esteli",
      category: "Cigars",
      image: "/images/p-4.png",
      price: 620,
      countInStock: 50,
      brand: "Montana",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Baccarat Nicaragua",
      category: "Cigars",
      image: "/images/p-5.jpeg",
      price: 420,
      countInStock: 50,
      brand: "Montana",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "601 Blue Label Maduro",
      category: "Cigars",
      image: "/images/p-6.png",
      price: 320,
      countInStock: 50,
      brand: "Montana",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
